/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class alternatif extends javax.swing.JFrame {

    /**
     * Creates new form alternatif
     */
    public alternatif() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getHapus() {
        return hapus;
    }

    public JButton getKriteria() {
        return kriteria;
    }

    public JButton getTambah() {
        return tambah;
    }

    public JTable getTbAlternatif() {
        return tbAlternatif;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tbAlternatif = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kriteria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);

        tbAlternatif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAlternatif.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tbAlternatif);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 730, 250));

        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 100, 40));

        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 100, 40));

        kriteria.setBorder(null);
        kriteria.setBorderPainted(false);
        kriteria.setContentAreaFilled(false);
        getContentPane().add(kriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/alternatif.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alternatif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kriteria;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbAlternatif;
    // End of variables declaration//GEN-END:variables
}
