/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class hasilPerhitungan extends javax.swing.JFrame {

    /**
     * Creates new form hasilPerhitungan
     */
    public hasilPerhitungan() {
        initComponents();
    }

    public JButton getTotalIP() {
        return totalIP;
    }

    public JButton getAlternatif() {
        return alternatif;
    }

    public JLabel getKriteria() {
        return kriteria;
    }

    public JButton getNext() {
        return next;
    }

    public JButton getPrev() {
        return prev;
    }

    public JTable getTabelKriteria() {
        return tabelKriteria;
    }

    public JLabel getTipeKriteria() {
        return tipeKriteria;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKriteria = new javax.swing.JTable();
        kriteria = new javax.swing.JLabel();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        tipeKriteria = new javax.swing.JLabel();
        alternatif = new javax.swing.JButton();
        totalIP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKriteria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 934, 442));

        kriteria.setText("Label Kriteria");
        getContentPane().add(kriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 85, -1));

        prev.setText("Kriteria Sebelumnya");
        getContentPane().add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 11, -1, -1));

        next.setText("Kriteria Selanjutnya");
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 11, -1, -1));

        tipeKriteria.setText("Label Tipe Kriteria");
        getContentPane().add(tipeKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));

        alternatif.setText("Alternatif");
        alternatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternatifActionPerformed(evt);
            }
        });
        getContentPane().add(alternatif, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 56, -1, -1));

        totalIP.setText("Lihat Total IP");
        getContentPane().add(totalIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternatifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternatifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasilPerhitungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternatif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JTable tabelKriteria;
    private javax.swing.JLabel tipeKriteria;
    private javax.swing.JButton totalIP;
    // End of variables declaration//GEN-END:variables
}
