/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class hasilPerhitungan extends javax.swing.JFrame {

    /**
     * Creates new form hasilPerhitungan
     */
    public hasilPerhitungan() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    public JLabel getNoKriteria() {
        return noKriteria;
    }

    public JButton getTotalIP() {
        return totalIP;
    }

    public JButton getAlternatif() {
        return alternatif;
    }

    public JLabel getKriteria() {
        return kriteria;
    }

    public JButton getNext() {
        return next;
    }

    public JButton getPrev() {
        return prev;
    }

    public JTable getTabelKriteria() {
        return tabelKriteria;
    }

    public JLabel getTipeKriteria() {
        return tipeKriteria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKriteria = new javax.swing.JTable();
        kriteria = new javax.swing.JLabel();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        tipeKriteria = new javax.swing.JLabel();
        alternatif = new javax.swing.JButton();
        totalIP = new javax.swing.JButton();
        noKriteria = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tabelKriteria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKriteria.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tabelKriteria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 930, 420));

        kriteria.setFont(new java.awt.Font("One Stroke Script LET", 0, 36)); // NOI18N
        kriteria.setText("Label Kriteria");
        getContentPane().add(kriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 330, -1));

        prev.setBorder(null);
        prev.setBorderPainted(false);
        prev.setContentAreaFilled(false);
        getContentPane().add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 170, 60));

        next.setBorder(null);
        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 170, 60));

        tipeKriteria.setFont(new java.awt.Font("One Stroke Script LET", 0, 36)); // NOI18N
        tipeKriteria.setText("nom");
        getContentPane().add(tipeKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 80, -1));

        alternatif.setBorder(null);
        alternatif.setBorderPainted(false);
        alternatif.setContentAreaFilled(false);
        getContentPane().add(alternatif, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 170, 60));

        totalIP.setBorder(null);
        totalIP.setBorderPainted(false);
        totalIP.setContentAreaFilled(false);
        getContentPane().add(totalIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 170, 60));

        noKriteria.setFont(new java.awt.Font("One Stroke Script LET", 0, 36)); // NOI18N
        noKriteria.setText("Nomor Kriteria");
        getContentPane().add(noKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Perhitungan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasilPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasilPerhitungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternatif;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JButton next;
    private javax.swing.JLabel noKriteria;
    private javax.swing.JButton prev;
    private javax.swing.JTable tabelKriteria;
    private javax.swing.JLabel tipeKriteria;
    private javax.swing.JButton totalIP;
    // End of variables declaration//GEN-END:variables
}
