/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class tambahKriteria extends javax.swing.JFrame {

    /**
     * Creates new form tambahKriteria
     */
    public tambahKriteria() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    public JButton getBatal() {
        return batal;
    }

    public JComboBox<String> getBobot() {
        return bobot;
    }

    public JComboBox<String> getMinmaks() {
        return minmaks;
    }

    public JTextField getNamaKriteria() {
        return namaKriteria;
    }

    public JTextField getParameterP() {
        return parameterP;
    }

    public JTextField getParameterQ() {
        return parameterQ;
    }

    public JButton getSimpan() {
        return simpan;
    }

    public JComboBox<String> getTipePref() {
        return tipePref;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaKriteria = new javax.swing.JTextField();
        parameterP = new javax.swing.JTextField();
        parameterQ = new javax.swing.JTextField();
        minmaks = new javax.swing.JComboBox<>();
        tipePref = new javax.swing.JComboBox<>();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        bobot = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaKriteria.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        getContentPane().add(namaKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 360, 50));

        parameterP.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        getContentPane().add(parameterP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 360, 50));

        parameterQ.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        getContentPane().add(parameterQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 360, 50));

        minmaks.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        minmaks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Minimasi", "Maksimasi" }));
        minmaks.setBorder(null);
        getContentPane().add(minmaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 360, 40));

        tipePref.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        tipePref.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "1. Usual Criterion", "2. Quasi Criterion", "3. Linear Criterion", "4. Level Criterion", "5. Linear Criterion and Indiference" }));
        getContentPane().add(tipePref, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 360, 40));

        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 130, 50));

        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 140, 50));

        bobot.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        bobot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        bobot.setBorder(null);
        getContentPane().add(bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 360, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahKriteria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahKriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> bobot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> minmaks;
    private javax.swing.JTextField namaKriteria;
    private javax.swing.JTextField parameterP;
    private javax.swing.JTextField parameterQ;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> tipePref;
    // End of variables declaration//GEN-END:variables
}
