/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class tambahNilaiKriteria extends javax.swing.JFrame {

    /**
     * Creates new form tambahNilaiKriteria
     */
    public tambahNilaiKriteria() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    public JButton getKonfirmasi() {
        return konfirmasi;
    }

    public JLabel getLabelAlternatif() {
        return labelAlternatif;
    }

    public JLabel getLabelKriteria() {
        return labelKriteria;
    }

    public JTextField getNilai() {
        return nilai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nilai = new javax.swing.JTextField();
        labelAlternatif = new javax.swing.JLabel();
        labelKriteria = new javax.swing.JLabel();
        konfirmasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nilai.setFont(new java.awt.Font("One Stroke Script LET", 0, 30)); // NOI18N
        nilai.setBorder(null);
        getContentPane().add(nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 280, 50));

        labelAlternatif.setFont(new java.awt.Font("One Stroke Script LET", 0, 36)); // NOI18N
        labelAlternatif.setText("Label Alternatif");
        getContentPane().add(labelAlternatif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        labelKriteria.setFont(new java.awt.Font("One Stroke Script LET", 0, 36)); // NOI18N
        labelKriteria.setText("Label Kriteria");
        getContentPane().add(labelKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 210, -1));

        konfirmasi.setBorder(null);
        konfirmasi.setBorderPainted(false);
        konfirmasi.setContentAreaFilled(false);
        getContentPane().add(konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahNilai.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahNilaiKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahNilaiKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahNilaiKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahNilaiKriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahNilaiKriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton konfirmasi;
    private javax.swing.JLabel labelAlternatif;
    private javax.swing.JLabel labelKriteria;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
